// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WorkoutGlobal.LoggingService.API.DbContext;

#nullable disable

namespace WorkoutGlobal.LoggingService.Api.Migrations
{
    [DbContext(typeof(LoggerContext))]
    partial class LoggerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WorkoutGlobal.LoggingService.API.Models.Log", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LogTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<int>("SeverityId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SeverityId");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("WorkoutGlobal.LoggingService.API.Models.Severity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("SeveriryDescription")
                        .HasColumnType("text");

                    b.Property<string>("SeverityName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Severities");
                });

            modelBuilder.Entity("WorkoutGlobal.LoggingService.API.Models.Log", b =>
                {
                    b.HasOne("WorkoutGlobal.LoggingService.API.Models.Severity", "SeverityLevel")
                        .WithMany("Logs")
                        .HasForeignKey("SeverityId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("SeverityLevel");
                });

            modelBuilder.Entity("WorkoutGlobal.LoggingService.API.Models.Severity", b =>
                {
                    b.Navigation("Logs");
                });
#pragma warning restore 612, 618
        }
    }
}
